author:
  avatar           : "/images/profile.png"
  name             : "Rafael Gonzalez-Manzanares, MD, PhD"
  bio              : "Cardiologist and researcher"
  location         : "Cordoba, Spain"
  employer         : "Reina Sofia University Hospital - Heart Failure and Transplant Unit"
  email            : "rafael.gonzalez@imibic.org"

  # Academic websites
  orcid            : "https://orcid.org/0000-0001-8446-7369"
  googlescholar    : "https://scholar.google.com/citations?user=UThL6p4AAAAJ&hl=es"
  pubmed           : "https://www.ncbi.nlm.nih.gov/pubmed/?term=rafael+gonzalez-manzanares"

  # Social media
  twitter          : "rafaelglezm"
